# Generated by Django 5.1.4 on 2025-02-02 11:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
