# Generated by Django 5.1.4 on 2025-02-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_jobvacancy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='description',
            field=models.TextField(),
        ),
    ]
