# Generated by Django 5.1.4 on 2025-02-02 11:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_alter_jobvacancy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
